services:
  - type: web
    name: login-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: AUTH0_DOMAIN
        value: dev-w4kmffqu86f3iz7k.us.auth0.com
      - key: AUTH0_CLIENT_ID
        value: UNICXAl1jF8qeyOj4sDWbBB2PoGhdOSy
      - key: AUTH0_AUDIENCE
        value: https://dev-w4kmffqu86f3iz7k.us.auth0.com/api/v2/
      - key: AUTH0_ISSUER
        value: https://dev-w4kmffqu86f3iz7k.us.auth0.com/
      - key: AUTH0_CALLBACK_URL
        value: https://login-app.onrender.com/callback 